### ISSUE TITLE
How to exec inside current fileset?

### ISSUE THREAD

**Issue by darkleaf** [degree9/boot-exec#11]
I want to run compiled js file with node but it fail with error.
boot-exec run command in own tmp dir, not current fileset.
How I can do following?

```clojure
(deftask dev []
  (comp
   (wait)
   (cljs :compiler-options {:target :nodejs})
   (exec :process "node" :arguments ["main.js"])))
```

**Comment by burn2delete** [comment]
The fileset is an abstraction, it doesn't actually exist on the filesystem.

What you are probably looking for is [degree9/boot-nodejs](https://github.com/degree9/boot-nodejs)

**Comment by darkleaf** [comment]
I need run compiled `main.js` with node.
`main.js` located in boot tmp dir.
I don't understand how I can run this script with boot-exec or boot-nodejs.
Can you write example?

**Comment by burn2delete** [comment]
If you already have a working project, then all you need is the `serve` task from boot-nodejs.

```(serve :script "main")```

**Comment by darkleaf** [comment]
https://github.com/degree9/boot-nodejs/blob/master/src/degree9/boot_nodejs.clj#L7
```
Could not locate cheshire/core__init.class or cheshire/core.clj on classpath.
app_1  |     file: "degree9/boot_nodejs.clj"
```

boot-nodejs don't define this dependency =(

**Comment by burn2delete** [comment]
@darkleaf boot-nodejs version `1.1.0` released

**Comment by darkleaf** [comment]
Cool!

Is it possible to add `sync! #(apply boot/sync! tmp (boot/output-dirs %))` for `boot-exec`?

https://github.com/degree9/boot-nodejs/blob/master/src/degree9/boot_nodejs.clj#L42

**Comment by burn2delete** [comment]
@darkleaf sorry for the late reply, I dont see this being a useful feature adding the sync line, simply because there is no way to determine if that is the intended behaviour of the executable being used.

If this request comes back around, I'll look at adding some kind of sync option.
