### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by mkarp** [degree9/boot-exec#20]
Hey there!

Can we please get a new version pointing to the latest commit on master?

Currently 1.0.0 is pointing to this commit https://github.com/degree9/boot-exec/commit/67460d29359d3838cac61dacbbd28f514ad57ceb which is 8-9 months old, and 1.1.0-SNAPSHOT is pointing to a newer commit https://github.com/degree9/boot-exec/commit/127a847f7fad457df170c0d68d86969aa620f839 but I can't see in any of the branches.

Thank you!

**Comment by burn2delete** [comment]
@mkarp done!

**Comment by mkarp** [comment]
Thank you!
