### ISSUE TITLE
Executing a process in a directory always adds that directory to the fileset

### ISSUE THREAD

**Issue by svdm** [degree9/boot-exec#5]
The `exec` task always calls `add-resource` on the target directory. This is no doubt useful for many cases (generating some assets in a process etc), but problematic when using `exec` in a build pipeline, because unintended files get added to the fileset.

I encountered this via `degree9/boot-semgit`, because executing a git task was adding the entire repo to the fileset (including `.git` directory) which would then be packaged in by boot's `jar` task. I figured I'd report it here because it can't be fixed in semgit without changes in exec.

My suggestion for fixing this would be to make the "add dir as resource" behavior toggle-able via a parameter, which `boot-semgit` could then use to disable it. 

Minimal repro case in a directory containing a `build.boot` with only a boot-exec dependency + require in it:

    $ boot exec -p ls -d . show -f 
    Executing Process: ls
    Process completed successfully...
    
    └── build.boot

The build file is added to the fileset even though it is not in a source/resource/asset directory.

**Comment by burn2delete** [comment]
In your example you are using the current directory as the execution location for boot exec. This is where your error is, that directory should be a temporary location made with something like `(tmp-dir!)`.

**Comment by svdm** [comment]
I understand, but there are some commands you have to run outside of a tempdir. For example, git commands must run in the repo root. It's what `boot-semgit` is doing e.g. here https://github.com/degree9/boot-semgit/blob/master/src/degree9/boot_semgit.clj#L16

So right now, using one of those git tasks adds your whole repo to the fileset. I could also report that as a bug in `boot-semgit`, but there's no way to fix it there without some change in `boot-exec` to make it not `add-resource` the current directory.

**Comment by burn2delete** [comment]
Try the version currently in master, i think this will need to be solved in semgit tho.

**Comment by svdm** [comment]
I was using 0.4.0, compared to that master only includes some readme-related commits, so I don't think that'll help.

Anyway, if this is intended behaviour I'll just write some tasks that use clj-jgit instead of exec'ing the binary. I'll close this issue.

**Comment by burn2delete** [comment]
The new version has an include option which should solve your problem, I'll do a push to clojars today. Also I'd be willing to accept jgit PR's for boot-semgit.

**Comment by svdm** [comment]
Thanks for adding the option, but I think you haven't pushed it to github? The newest commit here is still 06d27dd358.

**Comment by burn2delete** [comment]
@svdm sorry it was in my personal repo, flyboarder/boot-exec I have merged it in here, can you take a look?

**Comment by svdm** [comment]
Thanks, it works fine. You could opt to make `include` enabled by default, so as not to break backwards compatibility (doesn't make a difference for me, but I guess someone might be relying on it).

I did look into jgit, but any interaction with the remote that requires authentication is a major hassle, because you can't rely on git handling things (so you have to explicitly connect to a running ssh-agent, else fall back, etc etc). That's probably why clj-jgit doesn't offer any bindings for e.g. pushing. So right now calling the binary is by far the more practical way to make it Just Work.

**Comment by burn2delete** [comment]
This should now be solved.
